# Multuple Linear Regression

### 원 핫 인코딩 

In [2]:
import numpy as np
import pandas as pd
# import matplotlib.pyplot as plt
df = pd.read_csv("../data/MultipleLinearRegressionData.csv")
X = df.iloc[:,:-1]
y = df.iloc[:,-1]
X,y

(    hour  absent    place
 0    0.5       3     Home
 1    1.2       4  Library
 2    1.8       2     Cafe
 3    2.4       0     Cafe
 4    2.6       2     Home
 5    3.2       0     Home
 6    3.9       0  Library
 7    4.4       0  Library
 8    4.5       5     Home
 9    5.0       1     Cafe
 10   5.3       2     Cafe
 11   5.8       0     Cafe
 12   6.0       3  Library
 13   6.1       1     Cafe
 14   6.2       1  Library
 15   6.9       4     Home
 16   7.2       2     Cafe
 17   8.4       1     Home
 18   8.6       1  Library
 19  10.0       0  Library,
 0      10
 1       8
 2      14
 3      26
 4      22
 5      30
 6      42
 7      48
 8      38
 9      58
 10     60
 11     72
 12     62
 13     68
 14     72
 15     58
 16     76
 17     86
 18     90
 19    100
 Name: score, dtype: int64)

In [3]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(drop='first'), [2])], remainder='passthrough')
# 원핫 인코딩 할 컬럼 : [2]
# drop first => 범주가 3개('Home' , 'Library' 'Cafe') 인데  다중공선성 때문에 한 컬럼을 없앰  
X = ct.fit_transform(X)
X # 원데이터 앞쪽에 2개 컬럼이 추가됨 
# 1,0 => Home
# 0,1 => Library
# 0,0 => Cafe

array([[ 1. ,  0. ,  0.5,  3. ],
       [ 0. ,  1. ,  1.2,  4. ],
       [ 0. ,  0. ,  1.8,  2. ],
       [ 0. ,  0. ,  2.4,  0. ],
       [ 1. ,  0. ,  2.6,  2. ],
       [ 1. ,  0. ,  3.2,  0. ],
       [ 0. ,  1. ,  3.9,  0. ],
       [ 0. ,  1. ,  4.4,  0. ],
       [ 1. ,  0. ,  4.5,  5. ],
       [ 0. ,  0. ,  5. ,  1. ],
       [ 0. ,  0. ,  5.3,  2. ],
       [ 0. ,  0. ,  5.8,  0. ],
       [ 0. ,  1. ,  6. ,  3. ],
       [ 0. ,  0. ,  6.1,  1. ],
       [ 0. ,  1. ,  6.2,  1. ],
       [ 1. ,  0. ,  6.9,  4. ],
       [ 0. ,  0. ,  7.2,  2. ],
       [ 1. ,  0. ,  8.4,  1. ],
       [ 0. ,  1. ,  8.6,  1. ],
       [ 0. ,  1. , 10. ,  0. ]])

### 데이터 세트 분리

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2 , random_state=0)

### 다중선형 회귀 학습

In [5]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train, y_train)

LinearRegression()

### 예측 값과 실제 값 비교 (테스트 세트)

In [6]:
y_pred = reg.predict(X_test) # 테스트 세트로 예측 y_pred
y_pred

array([ 92.15457859,  10.23753043, 108.36245302,  38.14675204])

In [8]:
y_test # 테스트 y 값 y_test

18     90
1       8
19    100
8      38
Name: score, dtype: int64

In [10]:
reg.coef_# 집 , 도서관, 공부시간, 결석 횟수 ==> 계수들

array([-5.82712824, -1.04450647, 10.40419528, -1.64200104])

In [11]:
reg.intercept_

5.365006706544776

## 모델 평가

In [12]:
reg.score(X_train, y_train) # 훈련 세트

0.9623352565265527

In [15]:
reg.score(X_test, y_test) # 테스트 세트
# 테스트 세트 점수가 더 높으므로 좋은 모델이라 할수있음

0.9859956178877446