In [1]:
import numpy as np
import pandas as pd

## Basic operations

In [4]:
a = np.array([1, 2, 3, 4])
print(a)
print(a + 1)



[1 2 3 4]
[2 3 4 5]


In [5]:
2**a

array([ 2,  4,  8, 16], dtype=int32)

In [6]:
# 모든 산술은 요소별로 작동합니다.
b = np.ones(4) + 1
print(a - b)
print(a * b)

[-1.  0.  1.  2.]
[2. 4. 6. 8.]


In [7]:
j = np.arange(5)
2**(j + 1) - j

array([ 2,  3,  6, 13, 28])

In [8]:
#Python에서 수행하는 것보다 훨씬 빠릅니다
a = np.arange(10000)
%timeit a + 1  

l = range(10000)
%timeit [i+1 for i in l] 

2.96 µs ± 36.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
217 µs ± 26.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### 행렬곱셈

In [9]:
# 배열 곱셈은 행렬 곱셈이 아닙니다.
c = np.ones((3, 3))
c*c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# 행렬곱셈
c.dot(c)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])